SELECT apellido1,apellido2,nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1 DESC, apellido2 DESC,nombre DESC;
SELECT nombre,apellido1,apellido2 FROM persona WHERE telefono IS NULL and tipo = 'alumno';
SELECT * FROM persona WHERE tipo = 'alumno' AND year(fecha_nacimiento)= 1999;
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL And nif LIKE'%K%';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.nombre,persona.apellido1,persona.apellido2,departamento.nombre FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor INNER JOIN departamento ON departamento.id = profesor.id_departamento ORDER BY apellido1, persona.nombre ASC;
SELECT asignatura.nombre,curso_escolar.anyo_inicio,curso_escolar.anyo_fin FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE persona.nif = '26902806M';
SELECT DISTINCT departamento.nombre FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento INNER JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor INNER JOIN grado ON grado.id = asignatura.id_grado WHERE grado.id = 4;
SELECT DISTINCT persona.nombre,persona.apellido1,persona.apellido2 FROM persona INNER JOIN  alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.id = 5;
SELECT departamento.nombre, persona.apellido1,persona.apellido2,persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento ORDER BY departamento.nombre ASC,persona.apellido1 ASC,persona.apellido2 ASC, persona.nombre ASC;
SELECT departamento.nombre, persona.apellido1,persona.apellido2,persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento  WHERE departamento.nombre IS NULL ORDER BY departamento.nombre ASC,persona.apellido1 ASC,persona.apellido2 ASC, persona.nombre ASC;
SELECT departamento.nombre FROM departamento LEFT JOIN profesor ON profesor.id_departamento = departamento.id WHERE profesor.id_departamento IS NULL;
SELECT persona.id, persona.apellido1,persona.apellido2,persona.nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN asignatura ON asignatura.id_profesor = persona.id WHERE asignatura.id_profesor IS NULL AND persona.tipo = 'profesor';
SELECT asignatura.id,asignatura.nombre FROM asignatura WHERE asignatura.id_profesor IS NULL;
SELECT departamento.id,departamento.nombre FROM departamento,persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor LEFT JOIN curso_escolar ON curso_escolar.id = asignatura.curso WHERE departamento.nombre IS NULL;
SELECT COUNT(*) FROM persona WHERE persona.tipo = 'alumno';
SELECT COUNT(*) FROM persona WHERE year(fecha_nacimiento) = 1999 AND persona.tipo = 'alumno';
SELECT departamento.nombre, COUNT(profesor.id_departamento) FROM departamento LEFT JOIN profesor ON profesor.id_departamento = departamento.id GROUP BY departamento.nombre ORDER BY profesor.id_departamento DESC;
SELECT grado.nombre, COUNT(asignatura.id) FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre ORDER BY asignatura.nombre DESC;
SELECT grado.nombre, COUNT(asignatura.id) FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre HAVING COUNT(asignatura.id) > 40;
SELECT grado.nombre, asignatura.tipo,SUM(asignatura.creditos) FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre, asignatura.tipo ORDER BY SUM(asignatura.creditos) DESC;
SELECT curso_escolar.anyo_inicio,COUNT(DISTINCT alumno_se_matricula_asignatura.id_alumno) FROM curso_escolar INNER JOIN alumno_se_matricula_asignatura GROUP BY curso_escolar.id;
SELECT persona.id, persona.apellido1,persona.apellido2, COUNT(asignatura.id) FROM persona LEFT JOIN asignatura ON persona.id = asignatura.id_profesor WHERE persona.tipo = 'profesor' GROUP BY persona.id ORDER BY COUNT(asignatura.id_profesor) DESC;
SELECT * FROM persona WHERE persona.tipo = 'alumno' ORDER BY YEAR(fecha_nacimiento) DESC LIMIT 1;
SELECT persona.* FROM persona INNER JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor WHERE profesor.id_departamento IS NOT NULL AND asignatura.id_profesor IS NULL;
